version: '2'

volumes:
  orderer.testorderer.test:
  peer0.test1.test:
  peer0.test2.test:
  ca.test1.test:
  ca.test2.test:

networks:
  enet:
services:
  test1-ca:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-test1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.test1.test-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.test1.test-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/priv_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/test1.test/ca/:/etc/hyperledger/fabric-ca-server-config
      - ca.test1.test:/etc/hyperledger/fabric-ca-server
    container_name: ca.test1.test
    networks:
      - enet

  test2-ca:
    image: hyperledger/fabric-ca:latest
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-test2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.test2.test-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --port 8054 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.test2.test-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/priv_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/test2.test/ca/:/etc/hyperledger/fabric-ca-server-config
      - ca.test2.test:/etc/hyperledger/fabric-ca-server
    container_name: ca.test2.test
    networks:
      - enet

  orderer.testorderer.test:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.testorderer.test
    container_name: orderer.testorderer.test
    networks:
      - enet

  peer0.test1.test:
    container_name: peer0.test1.test
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.test1.test
    networks:
      - enet

  peer0.test2.test:
    container_name: peer0.test2.test
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.test2.test
    networks:
      - enet

  cli:
    container_name: test_cli
    image: hyperledger/fabric-tools:latest
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=system-channel
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.test1.test:7051
      - CORE_PEER_LOCALMSPID=Test1OrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/test1.test/peers/peer0.test1.test/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/test1.test/peers/peer0.test1.test/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/test1.test/peers/peer0.test1.test/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/test1.test/users/Admin@test1.test/msp

    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts/
        - ./eeeeeeego:/opt/gopath/src/github.com/hyperledger/fabric/peer/eeeeego/
    depends_on:
      - peer0.test1.test
      - peer0.test2.test
    networks:
      - enet

